package Project;

import sun.misc.BASE64Decoder;
import java.io.*;

public class Base64 {


    /* decode the base64 code generated by the avatar-cut feature.
       get the image by the code, and then save it to the file path.
     */

    public static boolean GenerateImage(String imgStr, String imgFilePath) {
        if (imgStr == null)
            return false;
        BASE64Decoder decoder = new BASE64Decoder();
        try {

            byte[] b = decoder.decodeBuffer(imgStr);
            for (int i = 0; i < b.length; ++i) {
                if (b[i] < 0) {
                    b[i] += 256;
                }
            }
            OutputStream out = new FileOutputStream(imgFilePath);
            out.write(b);
            out.flush();
            out.close();
            return true;
        } catch (Exception e) {
            return false;
        }
    }
}